// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// This file was generated by Prisma

import * as dotenv from "dotenv";
dotenv.config();

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",

  datasource: {
    provider: "postgresql",
    url: process.env.DATABASE_URL!,
  },
});


// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",

//   migrate: {
//     datasource: {
//       provider: "postgresql",
//       url: process.env.DATABASE_URL!,
//     },
//   },

//   studio: {
//     datasource: {
//       provider: "postgresql",
//       url: process.env.DATABASE_URL!,
//     },
//   },
// });
// ......................................

// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   datasource: {
//     db: {
//       provider: "postgresql",
//       url: process.env.DATABASE_URL!,
//     },
//   },
//   migrate: {
//     datasource: "db",
//   },
// });